name: ZNM2-LibWrt
on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
  actions: read
jobs:
  Build:
    uses: ./.github/workflows/Build-OpenWrt.yml
    permissions:
      contents: write
      actions: write
    with:
      repo_url: https://github.com/laipeng668/openwrt-6.x.git
      repo_branch: 25.12-nss
      config_file: configs/znm2.config
      firmware_tag: ZNM2
      kernel_file: kernel-6.12
      artifact_prefix: ZNM2
      manifest_file: libwrt-qualcommax-ipq60xx.manifest
      release_summary: >-
        兆能M2 (zn_m2) 硬改1G内存，无WiFi无USB，满血NSS，Aurora主题，SmartDNS防污染，WireGuard，DDNS，qosify硬件QoS，KMS，ttyd终端，apk包管理。
      remove_sqm_scripts_nss: false
      rename_qualcommax_to_nowifi: true
      delete_old_workflows: false
      package_extension: apk
